Update SNYK_INFRA.yml

diff --git a/.github/workflows/SNYK_INFRA.yml b/.github/workflows/SNYK_INFRA.yml
--- a/.github/workflows/SNYK_INFRA.yml
+++ b/.github/workflows/SNYK_INFRA.yml
@@ -1,4 +1,4 @@
-name: Snyk Terraform 8.6.2
+name: Snyk 8.6.3
 
 on:
   push:
@@ -34,7 +34,7 @@ jobs:
         run: ls -lh
 
       - name: Show SARIF file head (debug)
-        run: head -40 snyk-terraform.sarif
+        run: head -40 snyk-terraform.sarif || echo "SARIF file missing"
 
       - name: Fix SARIF severity (if needed)
         run: |
